{{- if and .Values.secrets.dbPassword .Values.secrets.sessionSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crossview.fullname" . }}-secrets
  namespace: {{ include "crossview.namespace" . }}
  labels:
    {{- include "crossview.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.secrets.dbPassword | quote }}
  session-secret: {{ .Values.secrets.sessionSecret | quote }}
{{- end }}

