apiVersion: v1
kind: Service
metadata:
  name: {{ include "crossview.fullname" . }}-service
  namespace: {{ include "crossview.namespace" . }}
  labels:
    {{- include "crossview.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "crossview.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
  {{- if and (ne .Values.service.type "ExternalName") .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- if and (eq .Values.service.sessionAffinity "ClientIP") .Values.service.sessionAffinityTimeout }}
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.service.sessionAffinityTimeout }}
  {{- end }}
  {{- end }}

