apiVersion: v2
name: crossview
description: A Helm chart for Crossview - Crossplane resource visualization and management platform
type: application
version: 1.0.0
appVersion: "1.0.0"
icon: https://corpobit.github.io/crossview/images/helm-logo.svg
keywords:
  - kubernetes
  - crossplane
  - visualization
  - management
home: https://github.com/corpobit/crossview
sources:
  - https://github.com/corpobit/crossview
maintainers:
  - name: Crossview Team
annotations:
  artifacthub.io/images: |
    - name: crossview
      image: corpobit/crossview:latest
    - name: postgres
      image: postgres:16-alpine
dependencies: []

