chart-dirs:
  - helm/crossview
validate-maintainers: false
check-version-increment: false
all:
  build-helm-deps: true
  lint-conf: lintconf.yaml
  validate-schema: true
  validate-maintainers: false
  check-version-increment: false
  test-values-schema: true
target-branch: main
remote: origin
chart-repos:
  - crossview=https://corpobit.github.io/crossview
lint:
  maintainers: false
  validate-maintainers: false
  yamllint:
    config:
      extends: default
      rules:
        line-length:
          max: 200
          level: warning
  helm:
    extra-args: --strict

